<?php
/**
 * Created by PhpStorm.
 * User: Hristo
 * Date: 10/1/2015
 * Time: 16:29
 */


namespace MVCProject\ViewModels;

class UserLoginViewModel
{
    private $id;
    private $name;
    private $password;
    private $water;
    private $food;
    private $dirt;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getWater()
    {
        return $this->water;
    }

    /**
     * @param mixed $water
     */
    public function setWater($water)
    {
        $this->water = $water;
    }

    /**
     * @return mixed
     */
    public function getFood()
    {
        return $this->food;
    }

    /**
     * @param mixed $food
     */
    public function setFood($food)
    {
        $this->food = $food;
    }

    /**
     * @return mixed
     */
    public function getDirt()
    {
        return $this->dirt;
    }

    /**
     * @param mixed $dirt
     */
    public function setDirt($dirt)
    {
        $this->dirt = $dirt;
    }






}